// SPDX-FileCopyrightText: 2026 SeisSol Group
//
// SPDX-License-Identifier: BSD-3-Clause
// SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
//
// SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff
#include "Expr/RtcGpu.h"

#include "Expr/Binding.h"
#include "Expr/Codegen.h"
#include "Expr/Lower.h"
#include "Expr/Program.h"
#include "Reader/Scripting/DataTable.h"

#include <cstdint>
#include <cstring>
#include <sstream>
#include <string>
#include <vector>

namespace seissol::expr {

namespace {

using reader::scripting::DataType;

const char* elementType(DataType type) {
  switch (type) {
  case DataType::F32:
    return "float";
  case DataType::F64:
    return "double";
  case DataType::I32:
    return "int";
  case DataType::I64:
    return "long long";
  }
  return "double";
}

std::string inputName(std::int32_t index) { return "in" + std::to_string(index); }
std::string outputName(std::int32_t index) { return "out" + std::to_string(index); }

// Addressing for the device kernel. Every column is `base + p * stride +
// offset`, read at its own element type and converted once into the compute
// type -- the same conversion Binding::gatherFrom performs on the host, in the
// same direction, so the two paths cannot disagree about an i32 column.
//
// The thread's point index is `p`, computed in the loop header; `l` is the
// lane-relative index the output tile would have used on the CPU. Only `p`
// appears here, because there is no tile.
std::string gpuLoadInput(std::int32_t index) {
  const std::string i = std::to_string(index);
  return "load_in" + i + "(in" + i + ", stride_in" + i + ", offset_in" + i + ", p)";
}
std::string gpuLoadPersistent(std::int32_t slot) {
  return "persistent[" + std::to_string(slot) + "ul * numPoints + p]";
}
std::string gpuStoreOutput(std::int32_t index) {
  const std::string i = std::to_string(index);
  return "store_out" + i + "(out" + i + ", stride_out" + i + ", offset_out" + i + ", p)";
}
std::string gpuStorePersistent(std::int32_t slot) {
  return "persistent[" + std::to_string(slot) + "ul * numPoints + p]";
}

void emitPrologue(std::ostringstream& out, GpuTarget target) {
  out << "// Generated by seissol::expr. The arithmetic is stringified from\n"
      << "// SEISSOL_EXPR_PW_LIST, the same table the interpreter evaluates.\n";
  if (target == GpuTarget::Hip) {
    // hip_runtime.h is what hiprtc expects to be present; the CUDA side gets
    // its built-ins from nvrtc without an include.
    out << "#include <hip/hip_runtime.h>\n";
  }
  out << "\n"
      << "// Lane indexing, factored out so the same source can be compiled and RUN on\n"
      << "// the host by a test that defines these differently. That is how the\n"
      << "// arithmetic is checked against the interpreter without a device.\n"
      << "#ifndef SEISSOL_EXPR_TID\n"
      << "#define SEISSOL_EXPR_TID (blockIdx.x * blockDim.x + threadIdx.x)\n"
      << "#define SEISSOL_EXPR_NTHREADS (gridDim.x * blockDim.x)\n"
      << "#define SEISSOL_EXPR_KERNEL extern \"C\" __global__\n"
      << "#endif\n\n";
}

/// One typed accessor per column, so the element type is resolved at
/// generation time and no per-point switch survives into the kernel.
void emitAccessors(std::ostringstream& out,
                   const GpuLayout& layout,
                   const std::string& computeType) {
  for (std::size_t i = 0; i < layout.inputs.size(); ++i) {
    const char* element = elementType(layout.inputs[i]);
    out << "__device__ inline " << computeType << " load_in" << i
        << "(const void* __restrict base, unsigned long stride, unsigned long offset,\n"
        << "    unsigned long p) {\n"
        << "  const char* bytes = (const char*)base + offset + p * stride;\n"
        << "  " << element << " value;\n"
        << "  __builtin_memcpy(&value, bytes, sizeof(value));\n"
        << "  return (" << computeType << ")value;\n"
        << "}\n";
  }
  for (std::size_t i = 0; i < layout.outputs.size(); ++i) {
    const char* element = elementType(layout.outputs[i]);
    // Returns a proxy-free lvalue-ish setter: emitted stores read
    // `store_outN(...) = value`, so this hands back a reference to a typed
    // location. A reference rather than a store function keeps
    // codegen::emitStageBody's store form identical across backends.
    out << "struct SeissolStore" << i << " {\n"
        << "  " << element << "* p;\n"
        << "  __device__ inline void operator=(" << computeType << " v) const { *p = (" << element
        << ")v; }\n"
        << "};\n"
        << "__device__ inline SeissolStore" << i << " store_out" << i
        << "(void* __restrict base, unsigned long stride, unsigned long offset,\n"
        << "    unsigned long p) {\n"
        << "  char* bytes = (char*)base + offset + p * stride;\n"
        << "  SeissolStore" << i << " s; s.p = (" << element << "*)bytes; return s;\n"
        << "}\n";
  }
  out << "\n";
}

void emitSignature(std::ostringstream& out,
                   const char* name,
                   const GpuLayout& layout,
                   const std::string& computeType) {
  out << "SEISSOL_EXPR_KERNEL void " << name << "(\n";
  for (std::size_t i = 0; i < layout.inputs.size(); ++i) {
    out << "    const void* __restrict " << inputName(static_cast<std::int32_t>(i))
        << ", unsigned long stride_in" << i << ", unsigned long offset_in" << i << ",\n";
  }
  for (std::size_t i = 0; i < layout.outputs.size(); ++i) {
    out << "    void* __restrict " << outputName(static_cast<std::int32_t>(i))
        << ", unsigned long stride_out" << i << ", unsigned long offset_out" << i << ",\n";
  }
  out << "    " << computeType << "* __restrict persistent,\n"
      << "    unsigned long numPoints, unsigned long first, unsigned long count)";
}

void emitStage(std::ostringstream& out,
               const char* name,
               const StageCode& stage,
               const std::vector<std::int32_t>& operands,
               const GpuLayout& layout,
               const std::string& computeType) {
  emitSignature(out, name, layout, computeType);
  out << " {\n";

  // Grid-stride loop, so the launch geometry is free to be whatever the driver
  // layer picks and a short range still uses every thread it was given.
  out << "  for (unsigned long l = SEISSOL_EXPR_TID; l < count; l += SEISSOL_EXPR_NTHREADS) {\n"
      << "    const unsigned long p = first + l;\n";

  codegen::StageAddressing addressing;
  addressing.loadInput = gpuLoadInput;
  addressing.loadPersistent = gpuLoadPersistent;
  addressing.storeOutput = gpuStoreOutput;
  addressing.storePersistent = gpuStorePersistent;

  codegen::emitStageBody(
      out, stage, operands, computeType, codegen::MathStyle::Unqualified, addressing, "    ");
  out << "  }\n}\n\n";
}

std::uint64_t mix(std::uint64_t hash, std::uint64_t value) {
  // FNV-1a style, which is what the rest of the fingerprints here use.
  hash ^= value;
  hash *= 0x100000001b3ULL;
  return hash;
}

} // namespace

const char* describe(GpuRejection rejection) {
  switch (rejection) {
  case GpuRejection::None:
    return "";
  case GpuRejection::Lookup:
    return "it samples a data grid, which the device backends do not support yet";
  case GpuRejection::ComputedColumn:
    return "a column is bound as a computed value, so the kernel has no address to read";
  case GpuRejection::Permuted:
    return "the point set had to be reordered to group it, and the permutation is host-side";
  case GpuRejection::PersistentState:
    return "it carries state or hoisted values, which live in a host-side buffer";
  case GpuRejection::HostPointer:
    return "at least one bound pointer is not reachable from the device";
  }
  return "";
}

GpuRejection gpuRejection(const LoweredProgram& lowered,
                          const Binding& binding,
                          bool (*deviceAccessible)(const void*)) {
  if (codegen::containsLookup(lowered)) {
    return GpuRejection::Lookup;
  }
  if (!binding.addressable()) {
    return GpuRejection::ComputedColumn;
  }
  if (!binding.permutation().empty()) {
    return GpuRejection::Permuted;
  }
  if (lowered.persistentSlotCount() > 0) {
    return GpuRejection::PersistentState;
  }
  if (deviceAccessible != nullptr) {
    for (const auto* set : {&binding.inputs(), &binding.outputs()}) {
      for (const auto& column : *set) {
        if (!deviceAccessible(column.view->base)) {
          return GpuRejection::HostPointer;
        }
      }
    }
  }
  return GpuRejection::None;
}

std::uint64_t GpuLayout::fingerprint() const {
  std::uint64_t hash = 0xcbf29ce484222325ULL;
  hash = mix(hash, inputs.size());
  for (const auto type : inputs) {
    hash = mix(hash, static_cast<std::uint64_t>(type));
  }
  hash = mix(hash, outputs.size());
  for (const auto type : outputs) {
    hash = mix(hash, static_cast<std::uint64_t>(type));
  }
  return hash;
}

GpuLayout gpuLayoutOf(const Binding& binding) {
  GpuLayout layout;
  layout.inputs.reserve(binding.inputs().size());
  for (const auto& column : binding.inputs()) {
    layout.inputs.push_back(column.tableType);
  }
  layout.outputs.reserve(binding.outputs().size());
  for (const auto& column : binding.outputs()) {
    layout.outputs.push_back(column.tableType);
  }
  return layout;
}

std::string emitGpuHostTrampoline(const GpuLayout& layout, const std::string& computeType) {
  std::ostringstream out;
  out << "extern \"C\" void seissol_expr_invoke(void** a) {\n"
      << "  seissol_expr_run(\n";
  std::size_t k = 0;
  const auto scalar = [&](const char* type) { out << "    *(" << type << "*)a[" << k++ << "]"; };
  for (std::size_t i = 0; i < layout.inputs.size(); ++i) {
    scalar("const void*");
    out << ", ";
    scalar("unsigned long");
    out << ", ";
    scalar("unsigned long");
    out << ",\n";
  }
  for (std::size_t i = 0; i < layout.outputs.size(); ++i) {
    scalar("void*");
    out << ", ";
    scalar("unsigned long");
    out << ", ";
    scalar("unsigned long");
    out << ",\n";
  }
  out << "    *(" << computeType << "**)a[" << k++ << "],\n";
  scalar("unsigned long");
  out << ", ";
  scalar("unsigned long");
  out << ", ";
  scalar("unsigned long");
  out << ");\n}\n";
  return out.str();
}

GpuArguments::GpuArguments(const Binding& binding, const KernelArgs& args, void* persistent) {
  // 3 scalars per column, plus persistent, numPoints, first, count.
  const std::size_t count = 3 * (binding.inputs().size() + binding.outputs().size()) + 4;
  storage_.reserve(count);
  pointers_.reserve(count);

  for (std::size_t i = 0; i < binding.inputs().size(); ++i) {
    const auto& column = binding.inputs()[i];
    const void* base =
        (i < args.inputCount && args.inputs[i] != nullptr) ? args.inputs[i] : column.view->base;
    add(&base, sizeof(base));
    const auto stride = static_cast<std::uint64_t>(column.view->byteStride);
    const auto offset = static_cast<std::uint64_t>(column.view->byteOffset);
    add(&stride, sizeof(stride));
    add(&offset, sizeof(offset));
  }
  for (std::size_t i = 0; i < binding.outputs().size(); ++i) {
    const auto& column = binding.outputs()[i];
    void* base =
        (i < args.outputCount && args.outputs[i] != nullptr) ? args.outputs[i] : column.view->base;
    add(&base, sizeof(base));
    const auto stride = static_cast<std::uint64_t>(column.view->byteStride);
    const auto offset = static_cast<std::uint64_t>(column.view->byteOffset);
    add(&stride, sizeof(stride));
    add(&offset, sizeof(offset));
  }

  add(&persistent, sizeof(persistent));
  const auto numPoints = static_cast<std::uint64_t>(binding.numPoints());
  const auto first = static_cast<std::uint64_t>(args.first);
  const auto span = static_cast<std::uint64_t>(args.count);
  add(&numPoints, sizeof(numPoints));
  add(&first, sizeof(first));
  add(&span, sizeof(span));
}

void GpuArguments::add(const void* value, std::size_t bytes) {
  storage_.emplace_back();
  std::memcpy(storage_.back().data(), value, bytes);
  pointers_.push_back(storage_.back().data());
}

std::string emitGpuSource(const Program& program,
                          const LoweredProgram& lowered,
                          const GpuLayout& layout,
                          GpuTarget target) {
  const std::string computeType = program.computeType() == ComputeType::F32 ? "float" : "double";

  std::ostringstream out;
  emitPrologue(out, target);
  emitAccessors(out, layout, computeType);
  if (lowered.hasPrecompute()) {
    emitStage(out,
              "seissol_expr_precompute",
              lowered.precompute(),
              lowered.operands(),
              layout,
              computeType);
  }
  emitStage(out, "seissol_expr_run", lowered.run(), lowered.operands(), layout, computeType);
  return out.str();
}

} // namespace seissol::expr
