// SPDX-FileCopyrightText: 2026 SeisSol Group
//
// SPDX-License-Identifier: BSD-3-Clause
// SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
//
// SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff
#include "Expr/RtcGpu.h"

#include "Expr/Backend.h"
#include "Expr/Binding.h"
#include "Expr/Codegen.h"
#include "Expr/Lower.h"
#include "Expr/Program.h"
#include "Reader/Scripting/DataTable.h"

#include <cstdint>
#include <cstring>
#include <sstream>
#include <string>
#include <vector>

namespace seissol::expr {

namespace {

using reader::scripting::DataType;

std::size_t elementSize(DataType type) {
  switch (type) {
  case DataType::F32:
    return sizeof(float);
  case DataType::F64:
    return sizeof(double);
  case DataType::I32:
    return sizeof(std::int32_t);
  case DataType::I64:
    return sizeof(std::int64_t);
  }
  return sizeof(double);
}

const char* elementType(DataType type) {
  switch (type) {
  case DataType::F32:
    return "float";
  case DataType::F64:
    return "double";
  case DataType::I32:
    return "int";
  case DataType::I64:
    return "long long";
  }
  return "double";
}

/// The element at `bytes`, of type `type`, as a double: exact for every type a column has but the
/// i64 beyond 2^53, which no uniform value is.
double readAsDouble(const char* bytes, DataType type) {
  switch (type) {
  case DataType::F32: {
    float value = 0;
    std::memcpy(&value, bytes, sizeof(value));
    return value;
  }
  case DataType::F64: {
    double value = 0;
    std::memcpy(&value, bytes, sizeof(value));
    return value;
  }
  case DataType::I32: {
    std::int32_t value = 0;
    std::memcpy(&value, bytes, sizeof(value));
    return value;
  }
  case DataType::I64: {
    std::int64_t value = 0;
    std::memcpy(&value, bytes, sizeof(value));
    return static_cast<double>(value);
  }
  }
  return 0;
}

// Addressing for the device kernel. Every column is `base + p * stride +
// offset`, read at its own element type and converted once into the compute
// type -- the same conversion Binding::gatherFrom performs on the host, in the
// same direction, so the two paths cannot disagree about an i32 column.
//
// The thread's point index is `p`, computed in the loop header; `l` is the
// lane-relative index the output tile would have used on the CPU. Only `p`
// appears here, because there is no tile.
std::string gpuLoadInput(std::int32_t index) {
  // The accessor of a column per cell takes its divisor and index as well; which one a column
  // has is decided when the accessors are emitted, so the call goes through a macro.
  const std::string i = std::to_string(index);
  return "LOAD_IN" + i + "(a, p)";
}
std::string gpuLoadState(std::int32_t state) {
  return "(*STATE_AT" + std::to_string(state) + "(a, p))";
}
std::string gpuLoadPersistent(std::int32_t slot) {
  return "a->persistent[" + std::to_string(slot) + " * a->numPoints + p]";
}
std::string gpuStoreOutput(std::int32_t index, const std::string& value) {
  const std::string i = std::to_string(index);
  return "store_out" + i + "(a->out" + i + ", a->stride_out" + i + ", a->offset_out" + i + ", p, " +
         value + ")";
}
std::string gpuStoreState(std::int32_t state, const std::string& value) {
  return "*STATE_AT" + std::to_string(state) + "(a, p) = " + value;
}
std::string gpuStorePersistent(std::int32_t slot, const std::string& value) {
  return "a->persistent[" + std::to_string(slot) + " * a->numPoints + p] = " + value;
}
std::string gpuMatrix(std::int32_t matrix) { return "a->matrix" + std::to_string(matrix); }
std::string gpuBlockBase(std::int32_t block) { return "a->block" + std::to_string(block); }
std::string gpuCellStride(std::int32_t block) {
  return "a->cellStride_block" + std::to_string(block);
}
std::string gpuModeStride(std::int32_t block) {
  return "a->modeStride_block" + std::to_string(block);
}
std::string gpuCellIndex(std::int32_t block) {
  return "a->cellIndex_block" + std::to_string(block);
}

/// OpenCL C needs an address space on every pointer that reaches global
/// memory; CUDA and HIP infer it. Emitted rather than hardcoded so the rest of
/// the generator stays dialect-agnostic.
const char* globalQualifier(GpuTarget target) {
  return target == GpuTarget::OpenCl ? "__global " : "";
}

/// `inline` on a device function: `__device__ inline` for CUDA/HIP, plain
/// `inline` for OpenCL C, which has no such qualifier and puts everything on
/// the device by construction.
const char* deviceFunction(GpuTarget target) {
  return target == GpuTarget::OpenCl ? "inline" : "__device__ inline";
}

void emitPrologue(std::ostringstream& out, GpuTarget target) {
  out << "// Generated by seissol::expr. The arithmetic is stringified from\n"
      << "// SEISSOL_EXPR_PW_LIST, the same table the interpreter evaluates.\n";
  if (target == GpuTarget::Hip) {
    // hip_runtime.h is what hiprtc expects to be present; the CUDA side gets
    // its built-ins from nvrtc without an include.
    out << "#include <hip/hip_runtime.h>\n";
  }
  if (target == GpuTarget::OpenCl) {
    // Not optional and not conditional on the compute type: an f32 program can
    // still carry an f64 column, and the accessor for it names `double`.
    out << "#pragma OPENCL EXTENSION cl_khr_fp64 : enable\n";
  }

  // One name for a 64-bit unsigned, because the dialects spell it differently
  // and the emitted body should not have to care. `unsigned long` would be
  // 32-bit on a Windows host and is not an OpenCL C type at all.
  out << "typedef " << (target == GpuTarget::OpenCl ? "ulong" : "unsigned long long")
      << " SeissolU64;\n\n";

  out << "// Lane indexing, factored out so the same source can be compiled and RUN on\n"
      << "// the host by a test that defines these differently. That is how the\n"
      << "// arithmetic is checked against the interpreter without a device.\n"
      << "#ifndef SEISSOL_EXPR_TID\n";
  if (target == GpuTarget::OpenCl) {
    out << "#define SEISSOL_EXPR_TID get_global_id(0)\n"
        << "#define SEISSOL_EXPR_NTHREADS get_global_size(0)\n"
        << "#define SEISSOL_EXPR_KERNEL __kernel\n";
  } else {
    out << "#define SEISSOL_EXPR_TID (blockIdx.x * blockDim.x + threadIdx.x)\n"
        << "#define SEISSOL_EXPR_NTHREADS (gridDim.x * blockDim.x)\n"
        << "#define SEISSOL_EXPR_KERNEL extern \"C\" __global__\n";
  }
  out << "#endif\n\n";
}

/// Whether input `i` is passed by value (see GpuLayout::inputUniform).
bool isUniform(const GpuLayout& layout, std::size_t i) {
  return i < layout.inputUniform.size() && layout.inputUniform[i];
}

/// One typed accessor per column, so the element type is resolved at
/// generation time and no per-point switch survives into the kernel.
///
/// The store is a FUNCTION rather than a reference-returning proxy: OpenCL C
/// has no operator overloading, and a second store form for one dialect is
/// exactly the kind of split this generator exists to avoid.
void emitAccessors(std::ostringstream& out,
                   const GpuLayout& layout,
                   const std::string& computeType,
                   GpuTarget target) {
  const std::string global = globalQualifier(target);
  const std::string fn = deviceFunction(target);

  for (std::size_t i = 0; i < layout.inputs.size(); ++i) {
    if (isUniform(layout, i)) {
      // the value itself, already in the compute type
      out << "#define LOAD_IN" << i << "(a, p) ((a)->value_in" << i << ")\n";
      continue;
    }
    const char* element = elementType(layout.inputs[i]);
    const bool perCell = i < layout.inputPerCell.size() && layout.inputPerCell[i];
    out << fn << " " << computeType << " load_in" << i << "(" << global
        << "const void* base, SeissolU64 stride, SeissolU64 offset, ";
    if (perCell) {
      out << "SeissolU64 divisor, " << global << "const unsigned int* index, ";
    }
    out << "SeissolU64 p) {\n";
    if (perCell) {
      // A column per cell: the point reads the element of its cell.
      out << "  const SeissolU64 e = index != 0 ? (SeissolU64)index[p / divisor] : p / divisor;\n";
    } else {
      out << "  const SeissolU64 e = p;\n";
    }
    // A typed load, not a byte copy. gpuRejection() has already established
    // that stride and offset are element multiples, so the address is
    // aligned -- and __builtin_memcpy is not something every device
    // frontend is guaranteed to lower well.
    out << "  " << global << "const char* bytes = (" << global
        << "const char*)base + offset + e * stride;\n"
        << "  return (" << computeType << ")(*(" << global << "const " << element << "*)bytes);\n"
        << "}\n";
    const std::string n = std::to_string(i);
    out << "#define LOAD_IN" << n << "(a, p) load_in" << n << "((a)->in" << n << ", (a)->stride_in"
        << n << ", (a)->offset_in" << n;
    if (perCell) {
      out << ", (a)->divisor_in" << n << ", (a)->index_in" << n;
    }
    out << ", p)\n";
  }
  for (std::size_t i = 0; i < layout.outputs.size(); ++i) {
    const char* element = elementType(layout.outputs[i]);
    out << fn << " void store_out" << i << "(" << global
        << "void* base, SeissolU64 stride, SeissolU64 offset, SeissolU64 p,\n"
        << "    " << computeType << " v) {\n"
        << "  " << global << "char* bytes = (" << global << "char*)base + offset + p * stride;\n"
        << "  *(" << global << element << "*)bytes = (" << element << ")v;\n"
        << "}\n";
  }
  if (layout.states > 0) {
    // A state lies per cell, like a block, and is read and written in place.
    out << fn << " " << global << computeType << "* state_at(" << global
        << "void* base, SeissolU64 pointsPerCell,\n"
        << "    SeissolU64 cellStride, SeissolU64 pointStride, " << global
        << "const unsigned int* cellIndex, SeissolU64 p) {\n"
        << "  const SeissolU64 c = p / pointsPerCell;\n"
        << "  const SeissolU64 m = cellIndex != 0 ? (SeissolU64)cellIndex[c] : c;\n"
        << "  return (" << global << computeType << "*)((" << global
        << "char*)base + m * cellStride + (p - c * pointsPerCell) * pointStride);\n"
        << "}\n";
    for (std::size_t i = 0; i < layout.states; ++i) {
      const std::string n = std::to_string(i);
      out << "#define STATE_AT" << n << "(a, p) state_at((a)->state" << n << ", (a)->ppc_state" << n
          << ", (a)->cellStride_state" << n << ", (a)->pointStride_state" << n
          << ", (a)->cellIndex_state" << n << ", p)\n";
    }
  }
  out << "\n";
}

/// The argument block: one by-value struct for CUDA and HIP, a flat parameter
/// list for OpenCL.
///
/// The struct is what makes the launch arity-independent, and getting the
/// scalar form wrong does not crash -- the parameters land a slot over, `count`
/// is read out of a pointer, and the kernel writes nothing at all. That is why
/// CUDA and HIP use it.
///
/// OpenCL C cannot: a struct passed as a KERNEL argument may not portably
/// contain pointers. So there the parameters are spelled out and immediately
/// gathered into a local struct, which the point function then takes by
/// pointer exactly as on the other targets. The fusion seam stays identical
/// across all three; only the outermost signature differs.
///
/// GpuArguments packs the fields once and offers both views, so the two orders
/// cannot drift.
void emitArgumentStruct(std::ostringstream& out,
                        const GpuLayout& layout,
                        const std::string& computeType,
                        GpuTarget target) {
  const std::string global = globalQualifier(target);
  out << "typedef struct {\n";
  for (std::size_t i = 0; i < layout.inputs.size(); ++i) {
    if (isUniform(layout, i)) {
      // eight bytes like every other field, so the image is a flat append (GpuArguments)
      out << "  " << computeType << " value_in" << i << ";\n";
      if (computeType == "float") {
        out << "  unsigned int pad_in" << i << ";\n";
      }
      continue;
    }
    out << "  " << global << "const void* in" << i << ";\n"
        << "  SeissolU64 stride_in" << i << ";\n"
        << "  SeissolU64 offset_in" << i << ";\n";
    if (i < layout.inputPerCell.size() && layout.inputPerCell[i]) {
      out << "  SeissolU64 divisor_in" << i << ";\n"
          << "  " << global << "const unsigned int* index_in" << i << ";\n";
    }
  }
  for (std::size_t i = 0; i < layout.outputs.size(); ++i) {
    out << "  " << global << "void* out" << i << ";\n"
        << "  SeissolU64 stride_out" << i << ";\n"
        << "  SeissolU64 offset_out" << i << ";\n";
  }
  // The matrices are pointers only: their form is baked in. A block is its base, its two strides
  // and its cell index.
  for (std::size_t i = 0; i < layout.matrices.size(); ++i) {
    out << "  " << global << "const void* matrix" << i << ";\n";
  }
  for (std::size_t i = 0; i < layout.blocks.size(); ++i) {
    out << "  " << global << "const void* block" << i << ";\n"
        << "  SeissolU64 cellStride_block" << i << ";\n"
        << "  SeissolU64 modeStride_block" << i << ";\n"
        << "  " << global << "const unsigned int* cellIndex_block" << i << ";\n";
  }
  for (std::size_t i = 0; i < layout.states; ++i) {
    out << "  " << global << "void* state" << i << ";\n"
        << "  SeissolU64 ppc_state" << i << ";\n"
        << "  SeissolU64 cellStride_state" << i << ";\n"
        << "  SeissolU64 pointStride_state" << i << ";\n"
        << "  " << global << "const unsigned int* cellIndex_state" << i << ";\n";
  }
  out << "  " << global << computeType << "* persistent;\n"
      << "  SeissolU64 numPoints;\n"
      << "  SeissolU64 first;\n"
      << "  SeissolU64 count;\n"
      << "} SeissolExprArgs;\n\n";
}

/// The flat parameter list, in the same order as the struct's fields.
void emitFlatParameters(std::ostringstream& out,
                        const GpuLayout& layout,
                        const std::string& computeType) {
  for (std::size_t i = 0; i < layout.inputs.size(); ++i) {
    if (isUniform(layout, i)) {
      out << "    " << computeType << " value_in" << i << ",\n";
      continue;
    }
    out << "    __global const void* in" << i << ", SeissolU64 stride_in" << i
        << ", SeissolU64 offset_in" << i << ",\n";
    if (i < layout.inputPerCell.size() && layout.inputPerCell[i]) {
      out << "    SeissolU64 divisor_in" << i << ", __global const unsigned int* index_in" << i
          << ",\n";
    }
  }
  for (std::size_t i = 0; i < layout.outputs.size(); ++i) {
    out << "    __global void* out" << i << ", SeissolU64 stride_out" << i
        << ", SeissolU64 offset_out" << i << ",\n";
  }
  for (std::size_t i = 0; i < layout.matrices.size(); ++i) {
    out << "    __global const void* matrix" << i << ",\n";
  }
  for (std::size_t i = 0; i < layout.blocks.size(); ++i) {
    out << "    __global const void* block" << i << ", SeissolU64 cellStride_block" << i
        << ", SeissolU64 modeStride_block" << i << ", __global const unsigned int* cellIndex_block"
        << i << ",\n";
  }
  for (std::size_t i = 0; i < layout.states; ++i) {
    out << "    __global void* state" << i << ", SeissolU64 ppc_state" << i
        << ", SeissolU64 cellStride_state" << i << ", SeissolU64 pointStride_state" << i
        << ", __global const unsigned int* cellIndex_state" << i << ",\n";
  }
  out << "    __global " << computeType << "* persistent, SeissolU64 numPoints,\n"
      << "    SeissolU64 first, SeissolU64 count";
}

/// Gather the flat parameters into a local struct, so the point function's
/// signature is the same on every target.
void emitFlatGather(std::ostringstream& out, const GpuLayout& layout) {
  out << "  SeissolExprArgs a;\n";
  for (std::size_t i = 0; i < layout.inputs.size(); ++i) {
    if (isUniform(layout, i)) {
      out << "  a.value_in" << i << " = value_in" << i << ";\n";
      continue;
    }
    out << "  a.in" << i << " = in" << i << "; a.stride_in" << i << " = stride_in" << i
        << "; a.offset_in" << i << " = offset_in" << i << ";\n";
    if (i < layout.inputPerCell.size() && layout.inputPerCell[i]) {
      out << "  a.divisor_in" << i << " = divisor_in" << i << "; a.index_in" << i << " = index_in"
          << i << ";\n";
    }
  }
  for (std::size_t i = 0; i < layout.outputs.size(); ++i) {
    out << "  a.out" << i << " = out" << i << "; a.stride_out" << i << " = stride_out" << i
        << "; a.offset_out" << i << " = offset_out" << i << ";\n";
  }
  for (std::size_t i = 0; i < layout.matrices.size(); ++i) {
    out << "  a.matrix" << i << " = matrix" << i << ";\n";
  }
  for (std::size_t i = 0; i < layout.blocks.size(); ++i) {
    out << "  a.block" << i << " = block" << i << "; a.cellStride_block" << i
        << " = cellStride_block" << i << "; a.modeStride_block" << i << " = modeStride_block" << i
        << "; a.cellIndex_block" << i << " = cellIndex_block" << i << ";\n";
  }
  for (std::size_t i = 0; i < layout.states; ++i) {
    out << "  a.state" << i << " = state" << i << "; a.ppc_state" << i << " = ppc_state" << i
        << "; a.cellStride_state" << i << " = cellStride_state" << i << "; a.pointStride_state" << i
        << " = pointStride_state" << i << "; a.cellIndex_state" << i << " = cellIndex_state" << i
        << ";\n";
  }
  out << "  a.persistent = persistent; a.numPoints = numPoints;\n"
      << "  a.first = first; a.count = count;\n";
}

void emitStage(std::ostringstream& out,
               const char* name,
               const StageCode& stage,
               const std::vector<std::int32_t>& operands,
               const GpuLayout& layout,
               const std::string& computeType,
               GpuTarget target,
               const codegen::ContractAddressing& contract) {
  // Emitted in two pieces, and that split is the interesting part.
  //
  // The POINT function is the expression and nothing else: no loop, no launch
  // geometry, no assumption about who calls it. A kernel that already owns a
  // loop over the same points can call it from inside, with the interior state
  // still in registers. That is how a projection fuses without this generator
  // learning what a GEMM is.
  //
  // The WRAPPER is the standalone form, and it is what the driver layer loads.
  out << deviceFunction(target) << " void " << name << "_point(\n"
      << "    " << (target == GpuTarget::OpenCl ? "" : "const ")
      << "SeissolExprArgs* a, SeissolU64 p) {\n";

  codegen::StageAddressing addressing;
  addressing.loadInput = gpuLoadInput;
  addressing.stateSlots = static_cast<std::int32_t>(layout.states);
  addressing.loadState = gpuLoadState;
  addressing.loadPersistent = gpuLoadPersistent;
  addressing.storeOutput = gpuStoreOutput;
  addressing.storeState = gpuStoreState;
  addressing.storePersistent = gpuStorePersistent;
  addressing.contract = &contract;

  codegen::emitStageBody(
      out, stage, operands, computeType, codegen::MathStyle::Unqualified, addressing, "  ");
  out << "}\n\n";

  out << "SEISSOL_EXPR_KERNEL void " << name << "(";
  if (target == GpuTarget::OpenCl) {
    out << "\n";
    emitFlatParameters(out, layout, computeType);
    out << ") {\n";
    emitFlatGather(out, layout);
  } else {
    out << "SeissolExprArgs a) {\n";
  }
  // Grid-stride loop, so the launch geometry is free to be whatever the driver
  // layer picks and a short range still uses every thread it was given.
  out << "  for (SeissolU64 l = SEISSOL_EXPR_TID; l < a.count; l += SEISSOL_EXPR_NTHREADS) {\n"
      << "    " << name << "_point(&a, a.first + l);\n"
      << "  }\n}\n\n";
}

std::uint64_t mix(std::uint64_t hash, std::uint64_t value) {
  // FNV-1a style, which is what the rest of the fingerprints here use.
  hash ^= value;
  hash *= 0x100000001b3ULL;
  return hash;
}

} // namespace

bool usesArgumentStruct(GpuTarget target) { return target != GpuTarget::OpenCl; }

const char* describe(GpuRejection rejection) {
  switch (rejection) {
  case GpuRejection::None:
    return "";
  case GpuRejection::Lookup:
    return "it samples a data grid, which the device backends do not support yet";
  case GpuRejection::ComputedColumn:
    return "a column is bound as a computed value, so the kernel has no address to read";
  case GpuRejection::Permuted:
    return "the point set had to be reordered to group it, and the permutation is host-side";
  case GpuRejection::StatefulProgram:
    return "it declares state with a non-zero initial value, which needs a fill kernel";
  case GpuRejection::HostPointer:
    return "at least one bound pointer is not reachable from the device";
  case GpuRejection::Misaligned:
    return "a column's stride or offset is not a whole number of its elements";
  }
  return "";
}

GpuRejection gpuRejection(const Program& program,
                          const LoweredProgram& lowered,
                          const Binding& binding,
                          bool (*deviceAccessible)(const void*)) {
  if (codegen::containsLookup(lowered)) {
    return GpuRejection::Lookup;
  }
  if (!binding.addressable()) {
    return GpuRejection::ComputedColumn;
  }
  if (!binding.permutation().empty()) {
    return GpuRejection::Permuted;
  }
  // Hoisted slots are fine: the buffer is zeroed and precompute writes them.
  // A state the kernel keeps itself is only fine when zero-initialised, for want of a fill; one
  // the table keeps is the table's to initialise.
  for (std::size_t i = 0; i < program.state().size(); ++i) {
    if (!binding.stateKept(i) && program.state()[i].initial != 0.0) {
      return GpuRejection::StatefulProgram;
    }
  }
  for (const auto* set : {&binding.inputs(), &binding.outputs()}) {
    for (const auto& column : *set) {
      const std::size_t element = elementSize(column.tableType);
      if (column.view->byteStride % element != 0 || column.view->byteOffset % element != 0) {
        return GpuRejection::Misaligned;
      }
    }
  }
  for (const auto& block : binding.blocks()) {
    const std::size_t element = elementSize(block.type);
    if (block.cellStride % element != 0 || block.modeStride % element != 0) {
      return GpuRejection::Misaligned;
    }
  }
  if (deviceAccessible != nullptr) {
    for (const auto* set : {&binding.inputs(), &binding.outputs()}) {
      for (const auto& column : *set) {
        if (column.view->uniform) {
          // read on the host when a call is packed
          continue;
        }
        if (!deviceAccessible(column.view->base) ||
            (column.view->index != nullptr && !deviceAccessible(column.view->index))) {
          return GpuRejection::HostPointer;
        }
      }
    }
    for (const auto& matrix : binding.matrices()) {
      if (!deviceAccessible(matrix.base)) {
        return GpuRejection::HostPointer;
      }
    }
    for (const auto& block : binding.blocks()) {
      if (!deviceAccessible(block.base) ||
          (block.cellIndex != nullptr && !deviceAccessible(block.cellIndex))) {
        return GpuRejection::HostPointer;
      }
    }
    for (std::size_t i = 0; i < binding.states().size(); ++i) {
      const auto& state = binding.states()[i];
      if (binding.stateKept(i) &&
          (!deviceAccessible(state.base) ||
           (state.cellIndex != nullptr && !deviceAccessible(state.cellIndex)))) {
        return GpuRejection::HostPointer;
      }
    }
  }
  return GpuRejection::None;
}

std::uint64_t GpuLayout::fingerprint() const {
  std::uint64_t hash = 0xcbf29ce484222325ULL;
  hash = mix(hash, inputs.size());
  for (const auto type : inputs) {
    hash = mix(hash, static_cast<std::uint64_t>(type));
  }
  for (const bool perCell : inputPerCell) {
    hash = mix(hash, perCell ? 1 : 0);
  }
  for (const bool uniform : inputUniform) {
    hash = mix(hash, uniform ? 2 : 0);
  }
  hash = mix(hash, outputs.size());
  for (const auto type : outputs) {
    hash = mix(hash, static_cast<std::uint64_t>(type));
  }
  hash = mix(hash, matrices.size());
  for (const auto type : matrices) {
    hash = mix(hash, static_cast<std::uint64_t>(type));
  }
  hash = mix(hash, blocks.size());
  for (const auto type : blocks) {
    hash = mix(hash, static_cast<std::uint64_t>(type));
  }
  hash = mix(hash, states);
  return hash;
}

GpuLayout gpuLayoutOf(const Binding& binding) {
  GpuLayout layout;
  layout.inputs.reserve(binding.inputs().size());
  for (const auto& column : binding.inputs()) {
    layout.inputs.push_back(column.tableType);
    layout.inputPerCell.push_back(column.view.has_value() && !column.view->pointwise());
    layout.inputUniform.push_back(column.view.has_value() && column.view->uniform);
  }
  layout.outputs.reserve(binding.outputs().size());
  for (const auto& column : binding.outputs()) {
    layout.outputs.push_back(column.tableType);
  }
  for (const auto& matrix : binding.matrices()) {
    layout.matrices.push_back(matrix.type);
  }
  for (const auto& block : binding.blocks()) {
    layout.blocks.push_back(block.type);
  }
  layout.states = binding.states().size();
  return layout;
}

std::string emitGpuHostTrampoline(const GpuLayout& /*layout*/, const std::string& /*computeType*/) {
  // One line, and independent of the program: the struct is what carries the
  // shape now. That is the point of the change -- a caller of the kernel has
  // nothing left to get wrong about arity or order.
  return "extern \"C\" void seissol_expr_invoke(void** a) {\n"
         "  seissol_expr_run(*(SeissolExprArgs*)a[0]);\n"
         "}\n";
}

std::string emitGpuHostTrampolineFlat(const GpuLayout& layout, const std::string& computeType) {
  // Generated from the layout because the flat form IS arity-dependent -- which
  // is exactly why the other targets do not use it.
  std::ostringstream out;
  out << "extern \"C\" void seissol_expr_invoke(const void** a) {\n  seissol_expr_run(\n";
  std::size_t k = 0;
  const auto arg = [&](const char* type) { out << "    *(" << type << "*)a[" << k++ << "]"; };
  for (std::size_t i = 0; i < layout.inputs.size(); ++i) {
    if (isUniform(layout, i)) {
      arg(("const " + computeType).c_str());
      out << ",\n";
      continue;
    }
    arg("const void* const");
    out << ", ";
    arg("const SeissolU64");
    out << ", ";
    arg("const SeissolU64");
    out << ",\n";
    if (i < layout.inputPerCell.size() && layout.inputPerCell[i]) {
      arg("const SeissolU64");
      out << ", ";
      arg("const unsigned int* const");
      out << ",\n";
    }
  }
  for (std::size_t i = 0; i < layout.outputs.size(); ++i) {
    arg("void* const");
    out << ", ";
    arg("const SeissolU64");
    out << ", ";
    arg("const SeissolU64");
    out << ",\n";
  }
  for (std::size_t i = 0; i < layout.matrices.size(); ++i) {
    arg("const void* const");
    out << ",\n";
  }
  for (std::size_t i = 0; i < layout.blocks.size(); ++i) {
    arg("const void* const");
    out << ", ";
    arg("const SeissolU64");
    out << ", ";
    arg("const SeissolU64");
    out << ", ";
    arg("const unsigned int* const");
    out << ",\n";
  }
  for (std::size_t i = 0; i < layout.states; ++i) {
    arg("void* const");
    out << ", ";
    arg("const SeissolU64");
    out << ", ";
    arg("const SeissolU64");
    out << ", ";
    arg("const SeissolU64");
    out << ", ";
    arg("const unsigned int* const");
    out << ",\n";
  }
  out << "    *(" << computeType << "* const*)a[" << k++ << "],\n";
  arg("const SeissolU64");
  out << ", ";
  arg("const SeissolU64");
  out << ", ";
  arg("const SeissolU64");
  out << ");\n}\n";
  return out.str();
}

GpuArguments::GpuArguments(const Binding& binding,
                           const KernelArgs& args,
                           void* persistent,
                           void* ownState) {
  // The byte image of the emitted SeissolExprArgs, in declaration order. Every
  // field is eight bytes wide and eight-byte aligned, which is why a flat
  // append works and no padding has to be reasoned about: pointers are 64-bit
  // on every target this runs on, and the scalars are `unsigned long long` for
  // exactly that reason.
  std::size_t perCellInputs = 0;
  std::size_t uniformInputs = 0;
  for (const auto& column : binding.inputs()) {
    perCellInputs += column.view->pointwise() ? 0 : 1;
    uniformInputs += column.view->uniform ? 1 : 0;
  }
  const std::size_t fields =
      3 * (binding.inputs().size() - uniformInputs + binding.outputs().size()) + uniformInputs +
      2 * perCellInputs + binding.matrices().size() + 4 * binding.blocks().size() +
      5 * binding.states().size() + 4;
  image_.reserve(fields * sizeof(std::uint64_t));

  const auto appendPointer = [this](const void* value) { append(&value, sizeof(value)); };
  const auto appendScalar = [this](std::uint64_t value) { append(&value, sizeof(value)); };

  for (std::size_t i = 0; i < binding.inputs().size(); ++i) {
    const auto& column = binding.inputs()[i];
    const void* base =
        (i < args.inputCount && args.inputs[i] != nullptr) ? args.inputs[i] : column.view->base;
    if (column.view->uniform) {
      // The value, read here and converted as Binding::gatherFrom converts it; a float is padded
      // to the eight bytes of a field (the struct declares the padding).
      const double value =
          readAsDouble(static_cast<const char*>(base) + column.view->byteOffset, column.tableType);
      if (binding.computeType() == ComputeType::F32) {
        const auto narrowed = static_cast<float>(value);
        append(&narrowed, sizeof(narrowed));
        image_.insert(image_.end(), sizeof(std::uint64_t) - sizeof(narrowed), 0);
      } else {
        append(&value, sizeof(value));
      }
      continue;
    }
    appendPointer(base);
    appendScalar(column.view->byteStride);
    appendScalar(column.view->byteOffset);
    if (!column.view->pointwise()) {
      appendScalar(column.view->divisor);
      appendPointer(column.view->index);
    }
  }
  for (std::size_t i = 0; i < binding.outputs().size(); ++i) {
    const auto& column = binding.outputs()[i];
    appendPointer((i < args.outputCount && args.outputs[i] != nullptr) ? args.outputs[i]
                                                                       : column.view->base);
    appendScalar(column.view->byteStride);
    appendScalar(column.view->byteOffset);
  }
  for (std::size_t i = 0; i < binding.matrices().size(); ++i) {
    const bool moved =
        i < args.matrixCount && args.matrices != nullptr && args.matrices[i] != nullptr;
    appendPointer(moved ? args.matrices[i] : binding.matrices()[i].base);
  }
  for (std::size_t i = 0; i < binding.blocks().size(); ++i) {
    const auto& block = binding.blocks()[i];
    const bool moved = i < args.blockCount && args.blocks != nullptr && args.blocks[i] != nullptr;
    appendPointer(moved ? args.blocks[i] : block.base);
    appendScalar(block.cellStride);
    appendScalar(block.modeStride);
    appendPointer(block.cellIndex);
  }
  // A state the table keeps where the call or the binding puts it; the others in `ownState`,
  // slot-major over the point set, like the Binding keeps them on the host.
  const std::size_t width =
      binding.states().empty() || binding.states().front().type == reader::scripting::DataType::F64
          ? sizeof(double)
          : sizeof(float);
  for (std::size_t i = 0; i < binding.states().size(); ++i) {
    const auto& state = binding.states()[i];
    if (binding.stateKept(i)) {
      const bool moved = i < args.stateCount && args.states != nullptr && args.states[i] != nullptr;
      appendPointer(moved ? args.states[i] : state.base);
    } else {
      appendPointer(ownState == nullptr
                        ? nullptr
                        : static_cast<char*>(ownState) + i * binding.numPoints() * width);
    }
    appendScalar(state.pointsPerCell);
    appendScalar(state.cellStride);
    appendScalar(state.pointStride);
    appendPointer(state.cellIndex);
  }
  appendPointer(persistent);
  appendScalar(binding.numPoints());
  appendScalar(args.first);
  appendScalar(args.count);

  // cuLaunchKernel wants an array of pointers TO the arguments. There is now
  // exactly one argument, so exactly one entry.
  pointers_.push_back(image_.data());
}

void GpuArguments::append(const void* value, std::size_t bytes) {
  const auto* source = static_cast<const unsigned char*>(value);
  fields_.push_back(Field{image_.size(), bytes});
  image_.insert(image_.end(), source, source + bytes);
}

std::string emitGpuSource(const Program& program,
                          const LoweredProgram& lowered,
                          const GpuLayout& layout,
                          GpuTarget target) {
  const std::string computeType = program.computeType() == ComputeType::F32 ? "float" : "double";

  // Every thread computes one point, so the lanes of one cell read the same block coefficient in
  // the same step: a broadcast rather than a gather, with no shared memory involved.
  codegen::ContractAddressing contract;
  for (const auto& matrix : program.matrices()) {
    contract.shapes.push_back(matrix.shape);
  }
  for (const auto type : layout.matrices) {
    contract.matrixTypes.emplace_back(codegen::elementTypeName(type));
  }
  for (const auto type : layout.blocks) {
    contract.blockTypes.emplace_back(codegen::elementTypeName(type));
  }
  contract.point = "p";
  contract.indexType = "SeissolU64";
  contract.global = globalQualifier(target);
  contract.matrix = gpuMatrix;
  contract.blockBase = gpuBlockBase;
  contract.cellStride = gpuCellStride;
  contract.modeStride = gpuModeStride;
  contract.cellIndex = gpuCellIndex;

  std::ostringstream out;
  emitPrologue(out, target);
  emitAccessors(out, layout, computeType, target);
  emitArgumentStruct(out, layout, computeType, target);
  if (lowered.hasPrecompute()) {
    emitStage(out,
              "seissol_expr_precompute",
              lowered.precompute(),
              lowered.operands(),
              layout,
              computeType,
              target,
              contract);
  }
  emitStage(out,
            "seissol_expr_run",
            lowered.run(),
            lowered.operands(),
            layout,
            computeType,
            target,
            contract);
  return out.str();
}

} // namespace seissol::expr
