jobs:
  - job:
    displayName: seissol-clang-tidy
    pool:
      vmImage: 'ubuntu-22.04'
    variables:
      - name: version
        value: 14
    steps:
      - bash: |
          set -euo pipefail
          export IFS=$'\n\t'
          export CTEST_OUTPUT_ON_FAILURE=1
          whoami
          pwd
          ls
          sudo apt-get update
          sudo apt-get install clang gfortran-11
          gcc --version
          sudo apt-get install -qq openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-103 libhdf5-openmpi-dev python3 python3-pip libmetis-dev libparmetis-dev clang-tidy libyaml-cpp-dev libeigen3-dev libomp-dev
          sudo pip3 install --upgrade pip
          sudo pip3 install 'numpy>=1.12.0'
          git clone --depth 1 --branch 1.17 https://github.com/hfp/libxsmm
          cd libxsmm
          make generator -j $(nproc)
          mkdir -p $HOME/bin
          cp bin/libxsmm_gemm_generator $HOME/bin
          export PATH=$HOME/bin:$PATH
          cd ..

          git clone --depth 1 --branch v1.0.0 https://github.com/SeisSol/easi.git    
          mkdir easi_build
          cd easi_build
          cmake -DASAGI=OFF -DIMPALAJIT=OFF -DCMAKE_INSTALL_PREFIX=$HOME ../easi
          make -j $(nproc) install
          cd ..
              
          git submodule update --init
        displayName: prepare-environment
      - bash: |
          mkdir -p build && cd build
          CMAKE_PREFIX_PATH=~ PKG_CONFIG_PATH=~/lib/pkgconfig/ CC=clang CXX=clang++ FC=gfortran cmake -DNETCDF=OFF -DMETIS=ON -DORDER=6 -DASAGI=OFF -DHDF5=ON -DCMAKE_BUILD_TYPE=Debug -DTESTING=ON -DLOG_LEVEL=warning -DLOG_LEVEL_MASTER=info -DHOST_ARCH=hsw -DPRECISION=double -DEQUATIONS=elastic -DNUMBER_OF_MECHANISMS=0 -DGEMM_TOOLS_LIST=LIBXSMM -DTESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          export PATH=$HOME/bin:$PATH
          make SeisSol-codegen
        displayName: cmake

      - bash: |
          cd build
          # clang-tidy can not handle -fprofile-abs-path, so we remove it from the compile commands.
          sed -i 's/-fprofile-abs-path //g' compile_commands.json
          ../.ci/tidy.sh ../ ./ -quiet -j $(nproc)
        displayName: clang-tidy
