stages:
    - build


build-cpu-image:
  stage: build
  tags:
    - image_builder
  allow_failure: false
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - export full_image_name="${CI_REGISTRY_USER}/${cpu_image_name}:${cpu_image_version}"
    - export file_changed=$(./.ci/is_changed.sh ./.ci/docker-cpu/Dockerfile.base)
    - export image_exists=$(./.ci/does_image_exists.sh "${full_image_name}")
    - echo "file changed=${file_changed}, image exists=${image_exists}"
    - >
      if [ $file_changed -eq 1 ] || [ $image_exists -eq 0 ]; then
        echo "building a new image - ${full_image_name}" ;
        docker build -t "${full_image_name}" -f ./.ci/docker-cpu/Dockerfile.base . ;
        docker push "${full_image_name}"
      else
        echo "image exists, Dockerfile was not modified. Skipping this step"
      fi


build-gpu-image:
  stage: build
  tags:
    - image_builder
  allow_failure: false
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - export full_image_name="${CI_REGISTRY_USER}/${gpu_image_name}:${gpu_image_version}"
    - export full_compiler_image_name="${CI_REGISTRY_USER}/gpu-ci-compiler-image:${gpu_image_version}"
    - export file_changed=$(./.ci/is_changed.sh ./.ci/docker-gpu)
    - export image_exists=$(./.ci/does_image_exists.sh "${full_image_name}")
    - echo "file changed=${file_changed}, image exists=${image_exists}"
    - >
      if [ $file_changed -eq 1 ] || [ $image_exists -eq 0 ]; then
        echo "building a new image - ${full_image_name}" ;
        docker build -t "${full_compiler_image_name}" -f ./.ci/docker-gpu/Dockerfile.compilers . ;
        docker build -t "${full_image_name}" --build-arg BASE_IMAGE_NAME=$full_compiler_image_name --build-arg SEISSOL_SHA_COMMIT=$CI_COMMIT_SHA -f ./.ci/docker-gpu/Dockerfile.base . ;
        docker push "${full_image_name}"
      else
        echo "image exists, Dockerfile was not modified. Skipping this step"
      fi
