# SPDX-FileCopyrightText: 2026 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
#
# SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

"""Memory characteristics of the target, as SeisSol needs them.

Two numbers come out of the architecture, and they answer different questions.
The vector width says how wide a load is, which is what tensors are padded to;
yateto derives it and calls it `alignment`. The cache line says what a buffer
should start on, which is what `alignas` wants. They coincide on most targets,
which is why one value has served for both, but they are not the same thing --
a machine with 128-byte lines and 128-bit vectors has them eight apart. Both
come from yateto, which derives them from the architecture name.
"""


def cacheline(arch):
    """Bytes a buffer should be aligned to on this target."""
    return arch.cacheline


def vector_size(arch):
    """Bytes a vector load covers, i.e. what tensors are padded to."""
    return arch.alignment


def emit_header(arch, output_dir, override_alignment=0, override_vectorsize=0):
    """Writes the memory characteristics for the C++ side to read.

    The build used to derive these a second time in CMake, from its own copy of
    the architecture table. Deriving them once here means the padding the
    kernels were generated with and the alignment the callers hand them cannot
    drift apart.
    """
    import os

    lines = [
        "// Generated by codegen/kernels/arch.py. Do not edit.",
        "",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        "namespace seissol {",
        "",
        "/// Bytes a buffer should start on.",
        f"constexpr std::size_t Alignment = "
        f"{override_alignment if override_alignment > 0 else cacheline(arch)};",
        "",
        "/// Bytes a vector load covers; tensors are padded to a multiple of it.",
        f"constexpr std::size_t Vectorsize = "
        f"{override_vectorsize if override_vectorsize > 0 else vector_size(arch)};",
        "",
        "} // namespace seissol",
        "",
    ]
    with open(os.path.join(output_dir, "alignment.h"), "w") as file:
        file.write("\n".join(lines))
