version: "3.3"

services:
  compilers:
    build:
      context: .
      dockerfile: Dockerfile.compilers
    image: seissol/gpu-ci-compiler-image:custom

  seissol-base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: seissol/gpu-ci-image:custom
    depends_on:
      - compilers
