# don't use a directory with whitespace
allowlist_dir="
    src/DynamicRupture
    src/Geometry
    src/Initializer/BatchRecorders
    src/Initializer/InitProcedure
    src/Initializer/Parameters
    src/Initializer/tree
    src/Modules
    src/Monitoring
    src/Numerical
    src/Parallel
    src/Physics
    src/Reader
    src/SourceTerm
    src/tests
    "

# NOTE: once the files of a directory are (almost) fully covered, consider moving it to allowlist_dir instead
allowlist_file="
    src/Equations/elastic/Model/datastructures.hpp
    src/Equations/elastic/Model/integrationData.hpp
    src/Equations/viscoelastic/Model/integrationData.hpp
    src/Equations/viscoelastic2/Model/datastructures.hpp
    src/Equations/viscoelastic2/Model/integrationData.hpp
    src/Equations/anisotropic/Model/datastructures.hpp
    src/Equations/anisotropic/Model/integrationData.hpp
    src/Equations/poroelastic/Model/datastructures.hpp
    src/Equations/poroelastic/Model/integrationData.hpp
    src/Initializer/BasicTypedefs.hpp
    src/Initializer/Boundary.h
    src/Initializer/DynamicRupture.h
    src/Initializer/DeviceGraph.h
    src/Initializer/GlobalData.h
    src/Initializer/GlobalData.cpp
    src/Initializer/InitialFieldProjection.h
    src/Initializer/InitialFieldProjection.cpp
    src/Initializer/InputAux.hpp
    src/Initializer/LTS.h
    src/Initializer/MemoryAllocator.h
    src/Initializer/MemoryAllocator.cpp
    src/Initializer/ParameterDB.h
    src/Initializer/ParameterDB.cpp
    src/Initializer/PointMapper.h
    src/Initializer/PointMapper.cpp
    src/Initializer/preProcessorMacros.hpp
    src/Initializer/time_stepping/GlobalTimestep.hpp
    src/Initializer/time_stepping/GlobalTimestep.cpp
    src/Kernels/common.hpp
    src/Kernels/PointSourceCluster.h
    src/Kernels/PointSourceClusterOnHost.h
    src/Kernels/PointSourceClusterOnHost.cpp
    src/Kernels/PointSourceClusterOnDevice.h
    src/Kernels/PointSourceClusterOnDevice.cpp
    src/Kernels/Receiver.h
    src/Kernels/Receiver.cpp
    src/Kernels/Touch.h
    src/Kernels/Touch.cpp
    src/Model/common_datastructures.hpp
    src/Model/plasticity.hpp
    src/ResultWriter/WaveFieldWriter.h
    src/ResultWriter/EnergyOutput.h
    src/ResultWriter/EnergyOutput.cpp
    src/SeisSol.h
    src/SeisSol.cpp
    src/main.cpp
    "
