# SPDX-FileCopyrightText: 2024 SeisSol Group
# 
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
#
# SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

version = 1

[[annotations]]
path = ["**/*.xml"]
SPDX-FileCopyrightText = "2012-2024 SeisSol Group"
SPDX-License-Identifier = "BSD-3-Clause"
