// SPDX-FileCopyrightText: 2022 SeisSol Group
//
// SPDX-License-Identifier: BSD-3-Clause
// SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
//
// SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

#ifndef SEISSOL_SRC_DYNAMICRUPTURE_FRICTIONLAWS_GPUIMPL_THERMALPRESSURIZATION_THERMALPRESSURIZATION_H_
#define SEISSOL_SRC_DYNAMICRUPTURE_FRICTIONLAWS_GPUIMPL_THERMALPRESSURIZATION_THERMALPRESSURIZATION_H_

#include "DynamicRupture/FrictionLaws/GpuImpl/BaseFrictionSolver.h"
#include "DynamicRupture/Misc.h"
#include "Initializer/Parameters/DRParameters.h"
#include "Kernels/Precision.h"
#include "Memory/Descriptor/DynamicRupture.h"

#include <array>
#include <cstddef>

namespace seissol::dr::friction_law::gpu {

/**
 * We follow Noda&Lapusta (2010) doi:10.1029/2010JB007780.
 * Define: \f$p, T\f$ pressure and temperature, \f$\Pi, \Theta\f$ fourier transform of pressure and
 * temperature respectively, \f$\Sigma = \Pi + \Lambda^\prime \Theta\f$. We solve equations (6) and
 * (7) with the method from equation(10).
 * \f[\begin{aligned}\text{Equation 6:} && \frac{\partial \Theta}{\partial t} =& -l^2 \alpha_{th}
 * \Theta + \frac{\Omega}{\rho c}\\ \text{Equation 7:} && \frac{\partial \Sigma}{\partial t} =& -l^2
 * \alpha_{hy} \Theta + (\Lambda + \Lambda^\prime) \frac{\Omega}{\rho c}\\\end{aligned}\f] with \f$
 * \Omega = \tau V \frac{\exp(-l^2 w^2 / 2) }{\sqrt{2\pi}}\f$. We define \f$\hat{l} = lw \in
 * [0,10]\f$ (see comment in [15]). Now, we can apply the solution procedure from equation (10) to
 * get:
 * \f[ \begin{aligned}\Theta(t+\Delta t) &= \frac{\Omega}{\rho c l^2 \alpha_{th}} \left[1 -
 * \exp\left(-l^2 \alpha_{th} \Delta t\right)\right] + \Theta(t)\exp(-l^2\alpha_{th} \Delta t)\\
 * &= \frac{\tau V}{\sqrt{2\pi}\rho c \left(\hat{l}/w\right)^2 \alpha_{th}} \exp(-\hat{l}^2/2)
 * \left[1 - \exp\left(-\left(\hat{l}/w\right)^2 \alpha_{th} \Delta t\right)\right]
 * + \Theta(t)\exp\left(-\left(\hat{l}/w\right)^2\alpha_{hy} \Delta t\right)\\\end{aligned}\f]
 * and
 * \f[ \begin{aligned}\Sigma(t+\Delta t) &= \frac{(\Lambda + \Lambda^\prime)\Omega}{\rho c l^2
 * \alpha_{hy}} \left[1 - \exp\left(-l^2 \alpha_{hy} \Delta t\right)\right] +
 * \Theta(t)\exp(-l^2\alpha_{hy} \Delta t)\\
 * &= \frac{(\Lambda + \Lambda^\prime)\tau V}{\sqrt{2\pi}\rho c \left(\hat{l}/w\right)^2
 * \alpha_{hy}} \exp(-\hat{l}^2/2) \left[1 - \exp\left(-\left(\hat{l}/w\right)^2 \alpha_{hy} \Delta
 * t\right)\right]
 * + \Sigma(t)\exp\left(-\left(\hat{l}/w\right)^2\alpha_{th} \Delta t\right)\\\end{aligned}\f]
 * We then compute the pressure and temperature update with an inverse Fourier transform from
 * \f$\Pi, \Theta\f$.
 */
class ThermalPressurization {
  public:
  /**
   * copies all parameters from the DynamicRupture LTS to the local attributes
   */
  static void copyStorageToLocal(FrictionLawData* data, DynamicRupture::Layer& layerData) {
    const auto place = seissol::initializer::AllocationPlace::Device;
    data->temperature = layerData.var<LTSThermalPressurization::Temperature>(place);
    data->pressure = layerData.var<LTSThermalPressurization::Pressure>(place);
    data->theta = layerData.var<LTSThermalPressurization::Theta>(place);
    data->sigma = layerData.var<LTSThermalPressurization::Sigma>(place);
    data->halfWidthShearZone = layerData.var<LTSThermalPressurization::HalfWidthShearZone>(place);
    data->hydraulicDiffusivity =
        layerData.var<LTSThermalPressurization::HydraulicDiffusivity>(place);
  }

  SEISSOL_DEVICE static real getFluidPressure(FrictionLawContext& __restrict ctx) {
    return ctx.data->pressure[ctx.ltsFace][ctx.pointIndex];
  }

  /**
   * Walk the wavenumber grid once and reduce the step to two coefficients.
   *
   * Everything the grid contributes is either carried over from the stored spectral state or
   * generated by this step's shear heating, and the generation is linear in tau * V. The step is
   * therefore an affine function of that one scalar,
   *   p(tau V) = pressureOffset + pressureSlope * tau V,
   * and the same for the temperature. Whatever slip rate the solve settles on, the pressure
   * follows from these coefficients without walking the grid again.
   */
  SEISSOL_DEVICE static void prepareFluidPressure(FrictionLawContext& __restrict ctx,
                                                  uint32_t timeIndex) {
    real temperatureDiffusion = 0.0;
    real temperatureSlope = 0.0;
    real pressureDiffusion = 0.0;
    real pressureSlope = 0.0;

    const real lambdaPrime = ctx.data->drParameters.undrainedTPResponse *
                             ctx.data->drParameters.thermalDiffusivity /
                             (ctx.data->hydraulicDiffusivity[ctx.ltsFace][ctx.pointIndex] -
                              ctx.data->drParameters.thermalDiffusivity);

    for (uint32_t tpGridPointIndex = 0; tpGridPointIndex < ctx.data->drParameters.tpGridPoints;
         tpGridPointIndex++) {
      const real squaredNormalizedTpGrid =
          misc::power<2>(ctx.args->tpGridPoints[tpGridPointIndex] /
                         ctx.data->halfWidthShearZone[ctx.ltsFace][ctx.pointIndex]);

      const real thetaTpGrid = ctx.data->drParameters.thermalDiffusivity * squaredNormalizedTpGrid;
      const real sigmaTpGrid =
          ctx.data->hydraulicDiffusivity[ctx.ltsFace][ctx.pointIndex] * squaredNormalizedTpGrid;
      const real preExpTheta = -thetaTpGrid * ctx.args->deltaT[timeIndex];
      const real preExpSigma = -sigmaTpGrid * ctx.args->deltaT[timeIndex];

      const std::size_t gridIndex =
          ctx.ltsFace * ctx.data->drParameters.tpGridPoints + tpGridPointIndex;
      const real scaledInverseFourierCoefficient =
          ctx.args->tpInverseFourierCoefficients[tpGridPointIndex] /
          ctx.data->halfWidthShearZone[ctx.ltsFace][ctx.pointIndex];

      // + F(t) exp(-A dt) in equation (10): what the spectral state carries over, which knows
      // nothing of this step's shear heating
      temperatureDiffusion += scaledInverseFourierCoefficient *
                              ctx.data->theta[gridIndex][ctx.pointIndex] * std::exp(preExpTheta);
      pressureDiffusion += scaledInverseFourierCoefficient *
                           ctx.data->sigma[gridIndex][ctx.pointIndex] * std::exp(preExpSigma);

      // B/A * (1 - exp(-A dt)) in equation (10), linear in tau * V
      // heatSource stores \exp(-\hat{l}^2 / 2) / \sqrt{2 \pi}
      const real omegaSlope = ctx.args->heatSource[tpGridPointIndex];
      temperatureSlope += scaledInverseFourierCoefficient * omegaSlope /
                          (ctx.data->drParameters.heatCapacity * thetaTpGrid) *
                          -std::expm1(preExpTheta);
      pressureSlope += scaledInverseFourierCoefficient * omegaSlope *
                       (ctx.data->drParameters.undrainedTPResponse + lambdaPrime) /
                       (ctx.data->drParameters.heatCapacity * sigmaTpGrid) *
                       -std::expm1(preExpSigma);
    }

    // Update pore pressure change: sigma = pore pressure + lambda' * temperature
    ctx.fluidPressure.temperatureOffset =
        temperatureDiffusion + ctx.data->drParameters.initialTemperature;
    ctx.fluidPressure.temperatureSlope = temperatureSlope;
    ctx.fluidPressure.pressureOffset = -(pressureDiffusion - lambdaPrime * temperatureDiffusion) +
                                       ctx.data->drParameters.initialPressure;
    ctx.fluidPressure.pressureSlope = -(pressureSlope - lambdaPrime * temperatureSlope);
  }

  /// the affine law of this step: p(tau V) = offset + slope * tau V; see prepareFluidPressure
  SEISSOL_DEVICE static real fluidPressureOffset(FrictionLawContext& __restrict ctx) {
    return ctx.fluidPressure.pressureOffset;
  }
  SEISSOL_DEVICE static real fluidPressureSlope(FrictionLawContext& __restrict ctx) {
    return ctx.fluidPressure.pressureSlope;
  }

  /// tau * V, the shear heating this point produces at its current state
  SEISSOL_DEVICE static real shearHeating(FrictionLawContext& __restrict ctx) {
    const real faultStrength =
        -ctx.data->mu[ctx.ltsFace][ctx.pointIndex] * ctx.initialVariables.normalStress;
    return faultStrength * ctx.initialVariables.localSlipRate;
  }

  /// Evaluate the affine law of the preceding pass at the shear heating of the current state.
  SEISSOL_DEVICE static void applyShearHeating(FrictionLawContext& __restrict ctx) {
    const real tauV = shearHeating(ctx);
    ctx.data->temperature[ctx.ltsFace][ctx.pointIndex] =
        ctx.fluidPressure.temperatureOffset + ctx.fluidPressure.temperatureSlope * tauV;
    ctx.data->pressure[ctx.ltsFace][ctx.pointIndex] =
        ctx.fluidPressure.pressureOffset + ctx.fluidPressure.pressureSlope * tauV;
  }

  /// Advance the spectral state by the shear heating the solve settled on, and store it.
  SEISSOL_DEVICE static void finalizeFluidPressure(FrictionLawContext& __restrict ctx,
                                                   uint32_t timeIndex) {
    const real tauV = shearHeating(ctx);
    const real lambdaPrime = ctx.data->drParameters.undrainedTPResponse *
                             ctx.data->drParameters.thermalDiffusivity /
                             (ctx.data->hydraulicDiffusivity[ctx.ltsFace][ctx.pointIndex] -
                              ctx.data->drParameters.thermalDiffusivity);

    for (uint32_t tpGridPointIndex = 0; tpGridPointIndex < ctx.data->drParameters.tpGridPoints;
         tpGridPointIndex++) {
      const real squaredNormalizedTpGrid =
          misc::power<2>(ctx.args->tpGridPoints[tpGridPointIndex] /
                         ctx.data->halfWidthShearZone[ctx.ltsFace][ctx.pointIndex]);
      const real thetaTpGrid = ctx.data->drParameters.thermalDiffusivity * squaredNormalizedTpGrid;
      const real sigmaTpGrid =
          ctx.data->hydraulicDiffusivity[ctx.ltsFace][ctx.pointIndex] * squaredNormalizedTpGrid;
      const real preExpTheta = -thetaTpGrid * ctx.args->deltaT[timeIndex];
      const real preExpSigma = -sigmaTpGrid * ctx.args->deltaT[timeIndex];

      const real omega = tauV * ctx.args->heatSource[tpGridPointIndex];
      const std::size_t gridIndex =
          ctx.ltsFace * ctx.data->drParameters.tpGridPoints + tpGridPointIndex;
      ctx.data->theta[gridIndex][ctx.pointIndex] =
          ctx.data->theta[gridIndex][ctx.pointIndex] * std::exp(preExpTheta) +
          omega / (ctx.data->drParameters.heatCapacity * thetaTpGrid) * -std::expm1(preExpTheta);
      ctx.data->sigma[gridIndex][ctx.pointIndex] =
          ctx.data->sigma[gridIndex][ctx.pointIndex] * std::exp(preExpSigma) +
          omega * (ctx.data->drParameters.undrainedTPResponse + lambdaPrime) /
              (ctx.data->drParameters.heatCapacity * sigmaTpGrid) * -std::expm1(preExpSigma);
    }

    // the coefficients of the preceding pass describe this very state, so the output follows from
    // them rather than from a second sum over the grid
    applyShearHeating(ctx);
  }
};
} // namespace seissol::dr::friction_law::gpu

#endif // SEISSOL_SRC_DYNAMICRUPTURE_FRICTIONLAWS_GPUIMPL_THERMALPRESSURIZATION_THERMALPRESSURIZATION_H_
