# SPDX-FileCopyrightText: 2025 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
#
# SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

---

name: 'seissol-test'
description: 'Build SeisSol and run Unit Tests'
inputs:
  cfg-equation:
    description: 'Equation to build for'
    required: true
    default: 'World'
  cfg-order:
    description: 'Order to build for'
    required: true
    default: 'World'
  cfg-precision:
    description: 'Precision to build for'
    required: true
    default: 'World'
  cfg-simulations:
    description: 'Simulation count to build for'
    required: true
    default: 'World'
  cfg-mechanisms:
    description: 'Mechanisms to build for (ignored but for visco)'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - id: build
      name: build-seissol
      shell: bash
      run: |
        # TODO: change to `-Wall -Werror` at some point
        EXTRA_FLAGS="-Wall"

        export CFLAGS="${EXTRA_FLAGS} ${CFLAGS}"
        export CXXFLAGS="${EXTRA_FLAGS} ${CXXFLAGS}"
        export FFLAGS="${EXTRA_FLAGS} ${FFLAGS}"

        export CC=${{env.cc}}
        export CXX=${{env.cxx}}
        export FC=${{env.fc}}

        mkdir -p /opt/seissol

        if [ $CC = nvc ]; then
          TESTING_COMMAND="mpirun -np 1 --oversubscribe --allow-run-as-root";
        else
          TESTING_COMMAND="";
        fi;

        mkdir -p build
        cd build

        ORDER=${{inputs.cfg-order}}
        EQUATION=${{inputs.cfg-equation}}
        MECHANISMS=${{inputs.cfg-mechanisms}}
        PRECISION=${{inputs.cfg-precision}}
        SIMULATIONS=${{inputs.cfg-simulations}}

        cmake .. \
          -GNinja \
          -DNEW_BINARY_NAMING=ON \
          -DTESTING_COMMAND="${TESTING_COMMAND}" \
          -DCMAKE_INSTALL_PREFIX=/opt/seissol \
          -DTESTING=${{env.tests}} \
          -DTESTING_GENERATED=${{env.tests}} \
          -DASAGI=ON \
          -DCMAKE_BUILD_TYPE=${{env.buildtype}} \
          -DHOST_ARCH=${{env.hostarch}} \
          -DDEVICE_CODEGEN=tensorforge \
          -DDEVICE_BACKEND=${{env.devicebackend}} \
          -DDEVICE_ARCH=${{env.devicearch}} \
          -DORDER=$ORDER \
          -DEQUATIONS=$EQUATION \
          -DPRECISION=$PRECISION \
          -DNUMBER_OF_MECHANISMS=$MECHANISMS \
          -DNUMBER_OF_FUSED_SIMULATIONS=$SIMULATIONS

        ninja install

        cd ..

    - name: test-seissol
      if: ${{ !cancelled() && steps.build.outcome == 'success' && inputs.tests == 'ON' }}
      shell: bash
      run: |
        cd build

        TEST_THREADS=$(($(nproc) * 4))
        ctest -j$TEST_THREADS --rerun-failed --output-on-failure

    - name: run-seissol-no-input
      if: ${{ !cancelled() && steps.build.outcome == 'success' && inputs.tests == 'ON' }}
      shell: bash
      run: |
        if [ ${{inputs.cc}} = nvc ]; then
          TESTING_COMMAND="mpirun -np 1 --oversubscribe --allow-run-as-root";
        else
          TESTING_COMMAND="";
        fi

        cd build

        set +e
        ${TESTING_COMMAND} ./seissol-cpu-*
        RETVAL_EXE=$?
        ./proxyseissol-cpu-*
        RETVAL_PROXY=$?
        set -e

        if [ $RETVAL_EXE -ne 133 ]; then
          echo "Unexpected exit code for SeisSol: ${RETVAL_EXE}"
          exit 1
        fi
        if [ $RETVAL_PROXY -ne 255 ]; then
          echo "Unexpected exit code for the SeisSol Proxy: ${RETVAL_PROXY}"
          exit 1
        fi

        echo "Success!"

    - name: run-proxy
      if: ${{ !cancelled() && steps.build.outcome == 'success' && inputs.tests == 'ON' }}
      shell: bash
      run: |
        cd build

        ./proxyseissol-cpu-* 100 1 ader
        ./proxyseissol-cpu-* 100 1 localwoader
        ./proxyseissol-cpu-* 100 1 local
        ./proxyseissol-cpu-* 100 1 neigh
        ./proxyseissol-cpu-* 100 1 all
        ./proxyseissol-cpu-* 100 1 neigh_dr
        ./proxyseissol-cpu-* 100 1 godunov_dr
        ./proxyseissol-cpu-* 100 1 all_dr

    - name: cleanup
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        rm -rf build
