// SPDX-FileCopyrightText: 2022 SeisSol Group
//
// SPDX-License-Identifier: BSD-3-Clause
// SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
//
// SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

#ifndef SEISSOL_SRC_DYNAMICRUPTURE_FRICTIONLAWS_CPUIMPL_THERMALPRESSURIZATION_THERMALPRESSURIZATION_H_
#define SEISSOL_SRC_DYNAMICRUPTURE_FRICTIONLAWS_CPUIMPL_THERMALPRESSURIZATION_THERMALPRESSURIZATION_H_

#include "DynamicRupture/FrictionLaws/TPCommon.h"
#include "DynamicRupture/Misc.h"
#include "Initializer/Parameters/DRParameters.h"
#include "Kernels/Precision.h"
#include "Memory/Descriptor/DynamicRupture.h"

#include <array>

namespace seissol::dr::friction_law::cpu {

/**
 * We follow Noda&Lapusta (2010) doi:10.1029/2010JB007780.
 * Define: \f$p, T\f$ pressure and temperature, \f$\Pi, \Theta\f$ fourier transform of pressure and
 * temperature respectively, \f$\Sigma = \Pi + \Lambda^\prime \Theta\f$. We solve equations (6) and
 * (7) with the method from equation(10).
 * \f[\begin{aligned}\text{Equation 6:} && \frac{\partial \Theta}{\partial t} =& -l^2 \alpha_{th}
 * \Theta + \frac{\Omega}{\rho c}\\ \text{Equation 7:} && \frac{\partial \Sigma}{\partial t} =& -l^2
 * \alpha_{hy} \Theta + (\Lambda + \Lambda^\prime) \frac{\Omega}{\rho c}\\\end{aligned}\f] with \f$
 * \Omega = \tau V \frac{\exp(-l^2 w^2 / 2) }{\sqrt{2\pi}}\f$. We define \f$\hat{l} = lw \in
 * [0,10]\f$ (see comment in [15]). Now, we can apply the solution procedure from equation (10) to
 * get:
 * \f[ \begin{aligned}\Theta(t+\Delta t) &= \frac{\Omega}{\rho c l^2 \alpha_{th}} \left[1 -
 * \exp\left(-l^2 \alpha_{th} \Delta t\right)\right] + \Theta(t)\exp(-l^2\alpha_{th} \Delta t)\\
 * &= \frac{\tau V}{\sqrt{2\pi}\rho c \left(\hat{l}/w\right)^2 \alpha_{th}} \exp(-\hat{l}^2/2)
 * \left[1 - \exp\left(-\left(\hat{l}/w\right)^2 \alpha_{th} \Delta t\right)\right]
 * + \Theta(t)\exp\left(-\left(\hat{l}/w\right)^2\alpha_{hy} \Delta t\right)\\\end{aligned}\f]
 * and
 * \f[ \begin{aligned}\Sigma(t+\Delta t) &= \frac{(\Lambda + \Lambda^\prime)\Omega}{\rho c l^2
 * \alpha_{hy}} \left[1 - \exp\left(-l^2 \alpha_{hy} \Delta t\right)\right] +
 * \Theta(t)\exp(-l^2\alpha_{hy} \Delta t)\\
 * &= \frac{(\Lambda + \Lambda^\prime)\tau V}{\sqrt{2\pi}\rho c \left(\hat{l}/w\right)^2
 * \alpha_{hy}} \exp(-\hat{l}^2/2) \left[1 - \exp\left(-\left(\hat{l}/w\right)^2 \alpha_{hy} \Delta
 * t\right)\right]
 * + \Sigma(t)\exp\left(-\left(\hat{l}/w\right)^2\alpha_{th} \Delta t\right)\\\end{aligned}\f]
 * We then compute the pressure and temperature update with an inverse Fourier transform from
 * \f$\Pi, \Theta\f$.
 */
class ThermalPressurization {
  public:
  explicit ThermalPressurization(const FrictionLawParameters& drParameters)
      : gridPoints_(drParameters.tpGridPoints),
        inverseFourierCoefficients_(drParameters.tpGridPoints),
        heatSource_(drParameters.tpGridPoints), drParameters_(drParameters) {}

  /**
   * copies all parameters from the DynamicRupture LTS to the local attributes
   */
  void copyStorageToLocal(DynamicRupture::Layer& layerData);

  /**
   * Walk the wavenumber grid once and reduce the step to two coefficients per point.
   *
   * Everything the grid contributes is either carried over from the stored spectral state or
   * generated by this step's shear heating, and the generation is linear in tau * V. The step is
   * therefore an affine function of that one scalar,
   *   p(tau V) = pressureOffset + pressureSlope * tau V,
   * and the same for the temperature. Whatever slip rate the solve settles on, the pressure
   * follows from these coefficients without touching the grid again.
   */
  void prepareFluidPressure(real deltaT, std::size_t ltsFace);

  /// Evaluate the affine law of the preceding pass at the shear heating of the given state.
  void applyShearHeating(const std::array<real, misc::NumPaddedPoints>& normalStress,
                         const real (*mu)[misc::NumPaddedPoints],
                         const std::array<real, misc::NumPaddedPoints>& slipRateMagnitude,
                         std::size_t ltsFace);

  /// Advance the spectral state by the shear heating the solve settled on, and store it.
  void finalizeFluidPressure(const std::array<real, misc::NumPaddedPoints>& normalStress,
                             const real (*mu)[misc::NumPaddedPoints],
                             const std::array<real, misc::NumPaddedPoints>& slipRateMagnitude,
                             real deltaT,
                             std::size_t ltsFace);

  [[nodiscard]] real getFluidPressure(std::size_t ltsFace, std::uint32_t pointIndex) const {
    return pressure_[ltsFace][pointIndex];
  }

  protected:
  real (*__restrict temperature_)[misc::NumPaddedPoints]{};
  real (*__restrict pressure_)[misc::NumPaddedPoints]{};
  /// the grid points of a face follow each other; see LTSThermalPressurization::Theta
  real (*__restrict theta_)[misc::NumPaddedPoints]{};
  real (*__restrict sigma_)[misc::NumPaddedPoints]{};
  real (*__restrict halfWidthShearZone_)[misc::NumPaddedPoints]{};
  real (*__restrict hydraulicDiffusivity_)[misc::NumPaddedPoints]{};

  private:
  /// the affine law of this step; see prepareFluidPressure
  std::array<real, misc::NumPaddedPoints> temperatureOffset_{};
  std::array<real, misc::NumPaddedPoints> temperatureSlope_{};
  std::array<real, misc::NumPaddedPoints> pressureOffset_{};
  std::array<real, misc::NumPaddedPoints> pressureSlope_{};

  /// the wavenumber grid and the coefficients on it, built for the configured point count
  tp::GridPoints<real> gridPoints_;
  tp::InverseFourierCoefficients<real> inverseFourierCoefficients_;
  tp::GaussianHeatSource<real> heatSource_;
  FrictionLawParameters drParameters_;
};
} // namespace seissol::dr::friction_law::cpu

#endif // SEISSOL_SRC_DYNAMICRUPTURE_FRICTIONLAWS_CPUIMPL_THERMALPRESSURIZATION_THERMALPRESSURIZATION_H_
