#!/bin/bash

VX_LITE=`which vx_lite`
VX_DIR=`dirname $VX_LITE`
VX_DIR=`dirname $VX_DIR`
MODEL_DIR=$VX_DIR/model

# Number of elements (not important for vx_lite)
read line

vx_lite -m $MODEL_DIR -z elev | awk '{print $1, $2, $3, $17, $18, $19}'