# SPDX-FileCopyrightText: 2024 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
#
# SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

name: bandit
on:
  - push

jobs:
  bandit:
    name: bandit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        name: checkout-seissol

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-pip
          pip install bandit==1.8.0
      
      # run for all, but don't fail the CI
      - name: run-bandit-all
        continue-on-error: True
        run: |
          set -euo pipefail
          bandit --quiet --recursive .

      # for now, only check for high-severity errors
      - name: run-bandit
        run: |
          set -euo pipefail
          bandit --quiet  --confidence-level high --severity-level high --recursive .
