# SPDX-FileCopyrightText: 2024 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
#
# SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

name: flake8
on:
  - push

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        name: checkout-seissol

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-pip
          pip install flake8

      - name: run-flake8
        run: |
          set -euo pipefail
          python -m flake8
