# SPDX-FileCopyrightText: 2024 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
#
# SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

# source (given as example) https://github.com/jgehrcke/github-repo-stats/wiki/Tutorial

name: github-repo-stats

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  update-stats:
    name: github-repo-stats
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'SeisSol/SeisSol' }} # disable on forks
    steps:
      - name: run-ghrs
        # Use latest release.
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          ghtoken: ${{ secrets.ghrs_github_api_token }}
