# SPDX-FileCopyrightText: 2024 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
#
# SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

name: codehub-hlrs-sync

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    if: ${{ github.repository == 'SeisSol/SeisSol' }} # disable on forks
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: cniethammer/git-repo-sync@cb1067d118c0c209bcded585b5c78e581bb0dfec
      with:
        target-url: 'https://codehub.hlrs.de/coes/cheese-2p/SeisSol/SeisSol.git'
        target-username: ${{ secrets.ACCESS_TOKEN_NAME }}
        target-token: ${{ secrets.ACCESS_TOKEN }}
