# SPDX-FileCopyrightText: 2024 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause
# SPDX-LicenseComments: Full text under /LICENSE and /LICENSES/
#
# SPDX-FileContributor: Author lists in /AUTHORS and /CITATION.cff

name: hadolint
on:
  - push

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-24.04
    container: ghcr.io/hadolint/hadolint:latest-alpine
    steps:
      - uses: actions/checkout@v4
      
      # hadolint also shows warnings+infos if not failing on errors
      - name: run-hadolint
        run: |
          set -euo pipefail
          find . -iname 'Dockerfile' | xargs hadolint --failure-threshold error
