# SPDX-FileCopyrightText: 2024 SeisSol Group
#
# SPDX-License-Identifier: BSD-3-Clause

name: restructuredtext-lint
on:
  - push

jobs:
  restructuredtext-lint:
    name: restructuredtext-lint
    runs-on: ubuntu-24.04
    if: False # disabled for now (only needed for SQAAS)
    steps:
      - uses: actions/checkout@v4
        name: checkout-seissol

      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get -y install python3 python3-pip
          pip install restructuredtext_lint==1.4.0

      - name: run-restructuredtext-lint
        run: |
          set -euo pipefail
          rst-lint .
